final List<Map<String, dynamic>> matchList = [
  {
    "match_id": 101,
    "league": "Premier League",
    "season": "2024/2025",
    "matchday": 30,
    "date": "2025-03-26",
    "time": "18:30",
    "stadium": "Old Trafford",
    "referee": "Michael Oliver",
    "home_team": {
      "name": "Man United",
      "logo": "assets/images/manutd_logo.png",
      "score": 2,
      "possession": "55%",
      "shots": 14,
      "shots_on_target": 7,
      "corners": 5,
      "fouls": 10,
      "yellow_cards": 1,
      "red_cards": 1,
      "lineup": [
        {"name": "David De Gea", "position": "GK", "number": 1},
        {"name": "Diogo Dalot", "position": "DF", "number": 20},
        {"name": "Raphaël Varane", "position": "DF", "number": 19},
        {"name": "Lisandro Martínez", "position": "DF", "number": 6},
        {"name": "Luke Shaw", "position": "DF", "number": 23},
        {"name": "Casemiro", "position": "MF", "number": 18},
        {"name": "Bruno Fernandes", "position": "MF", "number": 8},
        {"name": "Mason Mount", "position": "MF", "number": 7},
        {"name": "Marcus Rashford", "position": "FW", "number": 10},
        {"name": "Antony", "position": "FW", "number": 21},
        {"name": "Rasmus Højlund", "position": "FW", "number": 9},
      ],
      "substitutes": [
        {"name": "Tom Heaton", "position": "GK", "number": 22},
        {"name": "Harry Maguire", "position": "DF", "number": 5},
        {"name": "Christian Eriksen", "position": "MF", "number": 14},
        {"name": "Scott McTominay", "position": "MF", "number": 39},
        {"name": "Alejandro Garnacho", "position": "FW", "number": 49},
      ],
      "coach": "Erik ten Hag",
    },
    "away_team": {
      "name": "Chelsea",
      "logo": "assets/images/chelsea_logo.png",
      "score": 1,
      "possession": "45%",
      "shots": 10,
      "shots_on_target": 4,
      "corners": 3,
      "fouls": 12,
      "yellow_cards": 2,
      "red_cards": 0,
      "lineup": [
        {"name": "Robert Sánchez", "position": "GK", "number": 1},
        {"name": "Reece James", "position": "DF", "number": 24},
        {"name": "Thiago Silva", "position": "DF", "number": 6},
        {"name": "Ben Chilwell", "position": "DF", "number": 21},
        {"name": "Moisés Caicedo", "position": "MF", "number": 25},
        {"name": "Enzo Fernández", "position": "MF", "number": 8},
        {"name": "Conor Gallagher", "position": "MF", "number": 23},
        {"name": "Raheem Sterling", "position": "FW", "number": 17},
        {"name": "Nicolas Jackson", "position": "FW", "number": 15},
        {"name": "Mykhaylo Mudryk", "position": "FW", "number": 10},
      ],
      "substitutes": [
        {"name": "Djordje Petrovic", "position": "GK", "number": 28},
        {"name": "Marc Cucurella", "position": "DF", "number": 3},
        {"name": "Noni Madueke", "position": "FW", "number": 31},
        {"name": "Christopher Nkunku", "position": "FW", "number": 18},
      ],
      "coach": "Mauricio Pochettino",
    },
    "events": [
      {
        "minute": 15,
        "team": "Man United",
        "player": "Marcus Rashford",
        "type": "goal",
      },
      {
        "minute": 40,
        "team": "Chelsea",
        "player": "Raheem Sterling",
        "type": "goal",
      },
      {
        "minute": 45,
        "team": "Chelsea",
        "player": "Thiago Silva",
        "type": "yellow_card",
      },
      {
        "minute": 75,
        "team": "Man United",
        "player": "Bruno Fernandes",
        "type": "goal",
      },
      {
        "minute": 85,
        "team": "Chelsea",
        "player": "Reece James",
        "type": "yellow_card",
      },
      {
        "minute": 90,
        "team": "Man United",
        "player": "Casemiro",
        "type": "red_card",
      },
    ],
    "statistics": {
      "total_shots": {"home": 14, "away": 10},
      "shots_on_target": {"home": 7, "away": 4},
      "possession": {"home": "55%", "away": "45%"},
      "fouls": {"home": 10, "away": 12},
      "yellow_cards": {"home": 1, "away": 2},
      "red_cards": {"home": 1, "away": 0},
      "corners": {"home": 5, "away": 3},
      "offsides": {"home": 2, "away": 1},
      "passes": {"home": 520, "away": 460},
      "pass_accuracy": {"home": "86%", "away": "82%"},
    },
  },
  {
    "match_id": 102,
    "league": "Premier League",
    "season": "2024/2025",
    "matchday": 30,
    "date": "2025-03-26",
    "time": "21:00",
    "stadium": "Emirates Stadium",
    "referee": "Michael Oliver",
    "home_team": {
      "name": "Arsenal",
      "logo": "assets/images/arsenal_logo.png",
      "score": 2,
      "possession": "55%",
      "shots": 14,
      "shots_on_target": 7,
      "corners": 5,
      "fouls": 9,
      "yellow_cards": 1,
      "red_cards": 0,
      "lineup": [
        {"name": "Aaron Ramsdale", "position": "GK", "number": 1},
        {"name": "Ben White", "position": "DF", "number": 4},
        {"name": "William Saliba", "position": "DF", "number": 2},
        {"name": "Gabriel Magalhães", "position": "DF", "number": 6},
        {"name": "Oleksandr Zinchenko", "position": "DF", "number": 35},
        {"name": "Declan Rice", "position": "MF", "number": 41},
        {"name": "Martin Ødegaard", "position": "MF", "number": 8},
        {"name": "Kai Havertz", "position": "MF", "number": 29},
        {"name": "Bukayo Saka", "position": "FW", "number": 7},
        {"name": "Gabriel Jesus", "position": "FW", "number": 9},
        {"name": "Leandro Trossard", "position": "FW", "number": 19},
      ],
      "substitutes": [
        {"name": "David Raya", "position": "GK", "number": 22},
        {"name": "Takehiro Tomiyasu", "position": "DF", "number": 18},
        {"name": "Jorginho", "position": "MF", "number": 20},
        {"name": "Emile Smith Rowe", "position": "MF", "number": 10},
        {"name": "Eddie Nketiah", "position": "FW", "number": 14},
      ],
      "coach": "Mikel Arteta",
    },
    "away_team": {
      "name": "Brighton",
      "logo": "assets/images/brighton_logo.png",
      "score": 1,
      "possession": "45%",
      "shots": 10,
      "shots_on_target": 4,
      "corners": 3,
      "fouls": 12,
      "yellow_cards": 2,
      "red_cards": 0,
      "lineup": [
        {"name": "Jason Steele", "position": "GK", "number": 23},
        {"name": "Joel Veltman", "position": "DF", "number": 34},
        {"name": "Lewis Dunk", "position": "DF", "number": 5},
        {"name": "Jan Paul van Hecke", "position": "DF", "number": 29},
        {"name": "Pervis Estupiñán", "position": "DF", "number": 30},
        {"name": "Billy Gilmour", "position": "MF", "number": 11},
        {"name": "Pascal Groß", "position": "MF", "number": 13},
        {"name": "Adam Lallana", "position": "MF", "number": 14},
        {"name": "Kaoru Mitoma", "position": "FW", "number": 22},
        {"name": "Evan Ferguson", "position": "FW", "number": 28},
        {"name": "Danny Welbeck", "position": "FW", "number": 18},
      ],
      "substitutes": [
        {"name": "Bart Verbruggen", "position": "GK", "number": 1},
        {"name": "Tariq Lamptey", "position": "DF", "number": 2},
        {"name": "Facundo Buonanotte", "position": "MF", "number": 40},
        {"name": "João Pedro", "position": "FW", "number": 9},
        {"name": "Simon Adingra", "position": "FW", "number": 24},
      ],
      "coach": "Roberto De Zerbi",
    },
    "events": [
      {
        "minute": 12,
        "team": "Arsenal",
        "player": "Bukayo Saka",
        "type": "goal",
      },
      {
        "minute": 40,
        "team": "Brighton",
        "player": "Evan Ferguson",
        "type": "goal",
      },
      {
        "minute": 60,
        "team": "Arsenal",
        "player": "Gabriel Jesus",
        "type": "goal",
      },
      {
        "minute": 70,
        "team": "Brighton",
        "player": "Pascal Groß",
        "type": "yellow_card",
      },
      {
        "minute": 75,
        "team": "Arsenal",
        "player": "Oleksandr Zinchenko",
        "type": "yellow_card",
      },
      {
        "minute": 80,
        "team": "Brighton",
        "player": "Lewis Dunk",
        "type": "yellow_card",
      },
    ],
    "statistics": {
      "total_shots": {"home": 14, "away": 10},
      "shots_on_target": {"home": 7, "away": 4},
      "possession": {"home": "55%", "away": "45%"},
      "fouls": {"home": 9, "away": 12},
      "yellow_cards": {"home": 1, "away": 2},
      "red_cards": {"home": 0, "away": 0},
      "corners": {"home": 5, "away": 3},
      "offsides": {"home": 2, "away": 1},
      "passes": {"home": 520, "away": 480},
      "pass_accuracy": {"home": "86%", "away": "83%"},
    },
  },
  {
    "match_id": 103,
    "league": "Premier League",
    "season": "2024/2025",
    "matchday": 30,
    "date": "2025-03-26",
    "time": "21:00",
    "stadium": "St. James' Park",
    "referee": "Michael Oliver",
    "home_team": {
      "name": "Newcastle",
      "logo": "assets/images/newcastle_logo.png",
      "score": 2,
      "possession": "55%",
      "shots": 14,
      "shots_on_target": 7,
      "corners": 5,
      "fouls": 10,
      "yellow_cards": 2,
      "red_cards": 0,
      "lineup": [
        {"name": "Nick Pope", "position": "GK", "number": 22},
        {"name": "Kieran Trippier", "position": "DF", "number": 2},
        {"name": "Sven Botman", "position": "DF", "number": 4},
        {"name": "Fabian Schär", "position": "DF", "number": 5},
        {"name": "Dan Burn", "position": "DF", "number": 33},
        {"name": "Bruno Guimarães", "position": "MF", "number": 39},
        {"name": "Joelinton", "position": "MF", "number": 7},
        {"name": "Sean Longstaff", "position": "MF", "number": 36},
        {"name": "Anthony Gordon", "position": "FW", "number": 10},
        {"name": "Alexander Isak", "position": "FW", "number": 14},
        {"name": "Miguel Almirón", "position": "FW", "number": 24},
      ],
      "substitutes": [
        {"name": "Martin Dúbravka", "position": "GK", "number": 1},
        {"name": "Jamaal Lascelles", "position": "DF", "number": 6},
        {"name": "Elliot Anderson", "position": "MF", "number": 32},
        {"name": "Callum Wilson", "position": "FW", "number": 9},
        {"name": "Harvey Barnes", "position": "FW", "number": 17},
      ],
      "coach": "Eddie Howe",
    },
    "away_team": {
      "name": "Nottingham",
      "logo": "assets/images/nottingham_logo.png",
      "score": 1,
      "possession": "45%",
      "shots": 10,
      "shots_on_target": 4,
      "corners": 3,
      "fouls": 12,
      "yellow_cards": 3,
      "red_cards": 0,
      "lineup": [
        {"name": "Matt Turner", "position": "GK", "number": 1},
        {"name": "Serge Aurier", "position": "DF", "number": 24},
        {"name": "Willy Boly", "position": "DF", "number": 30},
        {"name": "Scott McKenna", "position": "DF", "number": 26},
        {"name": "Harry Toffolo", "position": "DF", "number": 15},
        {"name": "Orel Mangala", "position": "MF", "number": 5},
        {"name": "Ryan Yates", "position": "MF", "number": 22},
        {"name": "Danilo", "position": "MF", "number": 28},
        {"name": "Morgan Gibbs-White", "position": "FW", "number": 10},
        {"name": "Chris Wood", "position": "FW", "number": 11},
        {"name": "Taiwo Awoniyi", "position": "FW", "number": 9},
      ],
      "substitutes": [
        {"name": "Odysseas Vlachodimos", "position": "GK", "number": 23},
        {"name": "Neco Williams", "position": "DF", "number": 7},
        {"name": "Cheikhou Kouyaté", "position": "MF", "number": 8},
        {"name": "Callum Hudson-Odoi", "position": "FW", "number": 14},
        {"name": "Divock Origi", "position": "FW", "number": 27},
      ],
      "coach": "Nuno Espírito Santo",
    },
    "events": [
      {
        "minute": 15,
        "team": "Newcastle",
        "player": "Alexander Isak",
        "type": "goal",
      },
      {
        "minute": 40,
        "team": "Nottingham",
        "player": "Taiwo Awoniyi",
        "type": "goal",
      },
      {
        "minute": 65,
        "team": "Newcastle",
        "player": "Anthony Gordon",
        "type": "goal",
      },
      {
        "minute": 70,
        "team": "Nottingham",
        "player": "Ryan Yates",
        "type": "yellow_card",
      },
      {
        "minute": 78,
        "team": "Newcastle",
        "player": "Fabian Schär",
        "type": "yellow_card",
      },
      {
        "minute": 85,
        "team": "Nottingham",
        "player": "Morgan Gibbs-White",
        "type": "yellow_card",
      },
      {
        "minute": 90,
        "team": "Nottingham",
        "player": "Chris Wood",
        "type": "yellow_card",
      },
    ],
    "statistics": {
      "total_shots": {"home": 14, "away": 10},
      "shots_on_target": {"home": 7, "away": 4},
      "possession": {"home": "55%", "away": "45%"},
      "fouls": {"home": 10, "away": 12},
      "yellow_cards": {"home": 2, "away": 3},
      "red_cards": {"home": 0, "away": 0},
      "corners": {"home": 5, "away": 3},
      "offsides": {"home": 1, "away": 2},
      "passes": {"home": 510, "away": 460},
      "pass_accuracy": {"home": "87%", "away": "82%"},
    },
  },
  {
    "match_id": 104,
    "league": "Premier League",
    "season": "2024/2025",
    "matchday": 30,
    "date": "2025-03-26",
    "time": "21:00",
    "stadium": "Villa Park",
    "referee": "Anthony Taylor",
    "home_team": {
      "name": "Aston Villa",
      "logo": "assets/images/astonvilla_logo.png",
      "score": 1,
      "possession": "48%",
      "shots": 12,
      "shots_on_target": 5,
      "corners": 4,
      "fouls": 14,
      "yellow_cards": 2,
      "red_cards": 0,
      "lineup": [
        {"name": "Emiliano Martínez", "position": "GK", "number": 1},
        {"name": "Matty Cash", "position": "DF", "number": 2},
        {"name": "Pau Torres", "position": "DF", "number": 14},
        {"name": "Ezri Konsa", "position": "DF", "number": 4},
        {"name": "Lucas Digne", "position": "DF", "number": 12},
        {"name": "Douglas Luiz", "position": "MF", "number": 6},
        {"name": "Boubacar Kamara", "position": "MF", "number": 44},
        {"name": "John McGinn", "position": "MF", "number": 7},
        {"name": "Moussa Diaby", "position": "FW", "number": 19},
        {"name": "Ollie Watkins", "position": "FW", "number": 11},
        {"name": "Leon Bailey", "position": "FW", "number": 31},
      ],
      "substitutes": [
        {"name": "Robin Olsen", "position": "GK", "number": 25},
        {"name": "Tyrone Mings", "position": "DF", "number": 5},
        {"name": "Youri Tielemans", "position": "MF", "number": 8},
        {"name": "Bertrand Traoré", "position": "FW", "number": 9},
        {"name": "Jhon Durán", "position": "FW", "number": 24},
      ],
      "coach": "Unai Emery",
    },
    "away_team": {
      "name": "Tottenham",
      "logo": "assets/images/tottenham_logo.png",
      "score": 2,
      "possession": "52%",
      "shots": 15,
      "shots_on_target": 6,
      "corners": 5,
      "fouls": 10,
      "yellow_cards": 1,
      "red_cards": 0,
      "lineup": [
        {"name": "Guglielmo Vicario", "position": "GK", "number": 13},
        {"name": "Pedro Porro", "position": "DF", "number": 23},
        {"name": "Cristian Romero", "position": "DF", "number": 17},
        {"name": "Micky van de Ven", "position": "DF", "number": 37},
        {"name": "Destiny Udogie", "position": "DF", "number": 38},
        {"name": "Yves Bissouma", "position": "MF", "number": 8},
        {"name": "Pape Matar Sarr", "position": "MF", "number": 29},
        {"name": "James Maddison", "position": "MF", "number": 10},
        {"name": "Dejan Kulusevski", "position": "FW", "number": 21},
        {"name": "Heung-min Son", "position": "FW", "number": 7},
        {"name": "Richarlison", "position": "FW", "number": 9},
      ],
      "substitutes": [
        {"name": "Fraser Forster", "position": "GK", "number": 20},
        {"name": "Ben Davies", "position": "DF", "number": 33},
        {"name": "Giovani Lo Celso", "position": "MF", "number": 18},
        {"name": "Brennan Johnson", "position": "FW", "number": 22},
        {"name": "Manor Solomon", "position": "FW", "number": 11},
      ],
      "coach": "Ange Postecoglou",
    },
    "events": [
      {
        "minute": 12,
        "team": "Tottenham",
        "player": "Heung-min Son",
        "type": "goal",
      },
      {
        "minute": 33,
        "team": "Aston Villa",
        "player": "Ollie Watkins",
        "type": "goal",
      },
      {
        "minute": 50,
        "team": "Tottenham",
        "player": "James Maddison",
        "type": "goal",
      },
      {
        "minute": 65,
        "team": "Aston Villa",
        "player": "John McGinn",
        "type": "yellow_card",
      },
      {
        "minute": 72,
        "team": "Tottenham",
        "player": "Pedro Porro",
        "type": "yellow_card",
      },
      {
        "minute": 80,
        "team": "Aston Villa",
        "player": "Douglas Luiz",
        "type": "yellow_card",
      },
    ],
    "statistics": {
      "total_shots": {"home": 12, "away": 15},
      "shots_on_target": {"home": 5, "away": 6},
      "possession": {"home": "48%", "away": "52%"},
      "fouls": {"home": 14, "away": 10},
      "yellow_cards": {"home": 2, "away": 1},
      "red_cards": {"home": 0, "away": 0},
      "corners": {"home": 4, "away": 5},
      "offsides": {"home": 1, "away": 2},
      "passes": {"home": 480, "away": 500},
      "pass_accuracy": {"home": "85%", "away": "88%"},
    },
  },
  {
    "match_id": 105,
    "league": "Premier League",
    "season": "2024/2025",
    "matchday": 30,
    "date": "2025-03-26",
    "time": "23:30",
    "stadium": "Anfield",
    "referee": "Michael Oliver",
    "home_team": {
      "name": "Liverpool",
      "logo": "assets/images/liverpool_logo.png",
      "score": 2,
      "possession": "46%",
      "shots": 14,
      "shots_on_target": 7,
      "corners": 6,
      "fouls": 12,
      "yellow_cards": 2,
      "red_cards": 0,
      "lineup": [
        {"name": "Alisson Becker", "position": "GK", "number": 1},
        {"name": "Trent Alexander-Arnold", "position": "DF", "number": 66},
        {"name": "Virgil van Dijk", "position": "DF", "number": 4},
        {"name": "Ibrahima Konaté", "position": "DF", "number": 5},
        {"name": "Andrew Robertson", "position": "DF", "number": 26},
        {"name": "Alexis Mac Allister", "position": "MF", "number": 10},
        {"name": "Dominik Szoboszlai", "position": "MF", "number": 8},
        {"name": "Curtis Jones", "position": "MF", "number": 17},
        {"name": "Mohamed Salah", "position": "FW", "number": 11},
        {"name": "Darwin Núñez", "position": "FW", "number": 9},
        {"name": "Luis Díaz", "position": "FW", "number": 7},
      ],
      "substitutes": [
        {"name": "Caoimhin Kelleher", "position": "GK", "number": 62},
        {"name": "Joe Gomez", "position": "DF", "number": 2},
        {"name": "Harvey Elliott", "position": "MF", "number": 19},
        {"name": "Cody Gakpo", "position": "FW", "number": 18},
        {"name": "Diogo Jota", "position": "FW", "number": 20},
      ],
      "coach": "Jürgen Klopp",
    },
    "away_team": {
      "name": "Man City",
      "logo": "assets/images/mancity_logo.png",
      "score": 2,
      "possession": "54%",
      "shots": 16,
      "shots_on_target": 8,
      "corners": 5,
      "fouls": 8,
      "yellow_cards": 1,
      "red_cards": 0,
      "lineup": [
        {"name": "Ederson Moraes", "position": "GK", "number": 31},
        {"name": "Kyle Walker", "position": "DF", "number": 2},
        {"name": "Rúben Dias", "position": "DF", "number": 3},
        {"name": "John Stones", "position": "DF", "number": 5},
        {"name": "Joško Gvardiol", "position": "DF", "number": 24},
        {"name": "Rodri", "position": "MF", "number": 16},
        {"name": "Kevin De Bruyne", "position": "MF", "number": 17},
        {"name": "Bernardo Silva", "position": "MF", "number": 20},
        {"name": "Phil Foden", "position": "FW", "number": 47},
        {"name": "Erling Haaland", "position": "FW", "number": 9},
        {"name": "Jack Grealish", "position": "FW", "number": 10},
      ],
      "substitutes": [
        {"name": "Stefan Ortega", "position": "GK", "number": 18},
        {"name": "Manuel Akanji", "position": "DF", "number": 25},
        {"name": "Mateo Kovačić", "position": "MF", "number": 8},
        {"name": "Julián Álvarez", "position": "FW", "number": 19},
        {"name": "Rico Lewis", "position": "DF", "number": 82},
      ],
      "coach": "Pep Guardiola",
    },
    "events": [
      {
        "minute": 15,
        "team": "Man City",
        "player": "Erling Haaland",
        "type": "goal",
      },
      {
        "minute": 30,
        "team": "Liverpool",
        "player": "Mohamed Salah",
        "type": "goal",
      },
      {
        "minute": 55,
        "team": "Man City",
        "player": "Phil Foden",
        "type": "goal",
      },
      {
        "minute": 78,
        "team": "Liverpool",
        "player": "Darwin Núñez",
        "type": "goal",
      },
      {
        "minute": 82,
        "team": "Liverpool",
        "player": "Andrew Robertson",
        "type": "yellow_card",
      },
      {
        "minute": 88,
        "team": "Man City",
        "player": "Rodri",
        "type": "yellow_card",
      },
    ],
    "statistics": {
      "total_shots": {"home": 14, "away": 16},
      "shots_on_target": {"home": 7, "away": 8},
      "possession": {"home": "46%", "away": "54%"},
      "fouls": {"home": 12, "away": 8},
      "yellow_cards": {"home": 2, "away": 1},
      "red_cards": {"home": 0, "away": 0},
      "corners": {"home": 6, "away": 5},
      "offsides": {"home": 2, "away": 3},
      "passes": {"home": 470, "away": 510},
      "pass_accuracy": {"home": "86%", "away": "89%"},
    },
  },
];
